name: Generate Config

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'
  workflow_dispatch:
    
jobs:
  generate-readme:
    uses: Sambonic/parser/.github/workflows/create-config.yml@main
    with:
      github_username: ${{ github.repository_owner }}
      repo_name: ${{ github.repository }}
    secrets:
      token: ${{ secrets.README_GENERATOR_TOKEN }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
